name: matrimony_admin
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  # cupertino_icons: ^1.0.2
  # geolocator: ^13.0.1
  # geocoding: ^3.0.0
  # flutter_staggered_grid_view: ^0.7.0
  # firebase_messaging: ^14.2.1
  # shared_preferences: ^2.0.17
  # transparent_image: ^2.0.0
  # firebase_auth: ^4.2.5
  # google_sign_in: ^6.0.2
  # firebase_core: ^2.9.0
  # cloud_firestore: ^4.3.1
  # # cloud_firestore: ^0.14.0

  # # cloud_firestore_platform_interface: ^5.12.0
  # google_fonts: ^4.0.3
  # intl_phone_field: ^3.1.0
  # intl: ^0.19.0
  # age_calculator: ^1.0.0
  # flutter_signin_button: ^2.0.0
  # flutter_local_notifications: ^17.2.2
  # flutter_google_places: ^0.3.0
  # google_maps_flutter: ^2.2.3
  # line_icons: ^2.0.1
  # photo_view: ^0.15.0
  # expandable_text: ^2.3.0
  # firebase_storage: ^11.0.14
  # # image picker for choosing image
  # image_picker: ^1.1.2
  # #IMAGE cropper for cropping image 
  # image_cropper: ^4.0.1
  # bloc: ^8.1.1
  # equatable: ^2.0.5
  # screenshot: ^3.0.0
  # pdf: ^3.10.4
  # open_file: ^3.3.2
  # flutter_bloc: ^8.1.2
  # # image slider
  # flutter_image_slideshow: ^0.1.4
  # #video player
  # video_player: ^2.6.1
  # # share app 
  # share_plus: ^10.0.2
  # #rive animation
  # # rive: ^0.10.3
  # http: ^0.13.5
  # flutter_svg: ^2.0.9
  # awesome_snackbar_content: ^0.1.1
  # #video upload
  # file_picker: ^8.1.2
  # #country flag
  # # flutter_circle_flags_svg: ^1.0.4
  # # flutter animation
  # flutter_animate: ^4.1.1+1
  # # syncfusion_flutter_pdf: ^21.1.38
  # firebase_database: ^10.1.0
  # url_launcher: ^6.1.10
  # path_provider: ^2.0.14
  # flutter_launcher_icons: ^0.13.0
  # #responsive
  # sizer: ^3.0.3
  # flutter_polyline_points: ^1.0.0
  # get: ^4.6.6
  # csc_picker: ^0.2.7
  # cached_network_image: ^3.2.3
  
  # permission_handler: ^11.3.1

  # audioplayers: ^6.1.0
  # connectivity_plus: ^6.0.5
  # internet_connection_checker: ^1.0.0+1
  # cloudinary_public: ^0.23.1
  # email_validator: ^3.0.0
  # timezone: ^0.9.2
  # fl_chart: ^0.69.0
  # carousel_slider: ^5.0.0
  # # syncfusion_flutter_pdf: ^21.1.41
  # voice_message_package: ^2.2.1
  # chewie: ^1.5.0
  # any_link_preview: ^3.0.0
  # win32: ^5.5.4
  # loading_animation_widget: ^1.2.1
  # json_string: ^3.0.1
  # country_codes: ^3.1.0+2
  # googleapis_auth: ^1.4.1
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.3
  video_player: ^2.9.2
  chewie: ^1.8.5
  
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  get: ^4.6.6
  connectivity_plus: ^6.1.0
  flutter_signin_button: ^2.0.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  url_launcher: ^6.3.1
  google_sign_in: ^6.2.1
  # google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^1.0.0
  age_calculator: ^1.0.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  firebase_storage: ^12.3.3
  cloudinary_public: ^0.23.1
  path_provider: ^2.1.4
  cloud_firestore: ^5.4.4
  intl_phone_field: ^3.2.0
  firebase_messaging: ^15.1.3
  permission_handler: ^11.3.1
  socket_io_client: ^3.0.0
  profanity_filter: ^2.0.0
  firebase_database: ^11.1.4
  grouped_list: ^6.0.0
  any_link_preview: ^3.0.0
  voice_message_package: ^2.2.1
  font_awesome_flutter: ^9.2.0
  flutter_animate: ^4.5.0
  google_fonts: ^4.0.4
  flutter_image_slideshow: ^0.1.6
  photo_view: ^0.15.0
  ticker_text: ^2.1.0
  expandable_text: ^2.3.0
  standalone: ^1.1.0
  flutter_linkify: ^6.0.0
  internet_connection_checker: ^1.0.0+1
  screenshot: ^3.0.0
  pdf: ^3.11.1
  open_file: ^3.5.9
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  flutter_libphonenumber: ^2.5.1 
  share_plus: ^10.1.1
  googleapis_auth: ^1.4.1
  flutter_webrtc: ^0.12.11
  vibration: ^3.1.3
  loading_animation_widget: ^1.3.0
  json_string: ^3.0.1
  # csc_picker: ^0.2.7
  line_icons: ^2.0.3
  audioplayers: ^6.4.0
  file_picker: ^9.2.1
  country_codes: ^3.3.0
  email_validator: ^3.0.0
  fl_chart: ^0.70.2
  flutter_staggered_grid_view: ^0.7.0
  transparent_image: ^2.0.1
  bloc: ^9.0.0
  pull_to_refresh: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Sans-serif
      fonts:
        - asset: assets/arial.ttf
    - family: Serif
      fonts:
        - asset: assets/times_new_roman.ttf
    - family: Showg
      fonts:
        - asset: assets/SHOWG.ttf  

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/icons/
    - assets/
    - assets/sound/
    - assets/images/
    - lib/Assets/images/search.png
    - lib/Assets/countryModel/assets/country.json
    - RiveAssets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
